# Sample configuration file
---
products:
  - name: mongo # Product name, verify on https://endoflife.date/
    releases: # Release cycles you want to track, verify cycle name on https://endoflife.date/
      - "8.0"
      - "7.0"
  - name: redis
    releases:
      - latest
  - name: ubuntu
    all_releases: true # Fetch all available release cycles for this product (ignores 'releases' field if set)
    releases:
      - latest
